#!/bin/bash

set -e

for cmd in kubectl helm; {
    if ! command -v $cmd &> /dev/null
    then
        echo "$cmd not found"
        exit 1
    fi
}

# OPTIONAL: as part of the 'end to end' testing, you can install the
# *k8s-diagrams* tool in your $PATH to enable the automatic generation
# of PNG images showing all the different components installed and
# the relationship between them.
# https://github.com/trois-six/k8s-diagrams/releases/tag/v0.0.6

generate_k8s_images=true
if ! command -v k8s-diagrams -h &> /dev/null
then
    generate_k8s_images=false
fi

# Also, to convert the dot files generated by k8s-diagrams into PNG
# images, it is required to install the graphviz package.
if ! command -v dot -V &> /dev/null
then
    generate_k8s_images=false
fi

function finish {
  kubectl delete namespace plone-helm
}
trap finish EXIT

kubectl create namespace plone-helm

for helm_name in plone6-volto-zeo plone6-classic-pg plone6-volto-pg plone6-volto-pg-nginx-varnish; {
    echo Testing $helm_name

    helm lint ./$helm_name

    helm dependency update ./$helm_name
    helm dependency list ./$helm_name

    helm install -n plone-helm myplone ./$helm_name

    sleep 5

    if [ "$generate_k8s_images" = true ]; then
        dotdir="$(pwd)/$helm_name/diagrams"
        pngdir="$(pwd)/img/$helm_name"

        # wait more time, k8s deployment time may vary
        sleep 300

        rm -rf $dotdir
        k8s-diagrams --namespace plone-helm \
                     --outputDirectory $dotdir \
                     --label "helm $helm_name"
        mkdir -p $pngdir
        cd $dotdir
        dot -Tpng k8s.dot > $pngdir/k8s.png
        cd -
    fi

    helm uninstall -n plone-helm myplone
}
