apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zeo.fullname" . }}
  labels:
    {{- include "zeo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "zeo.fullname" . }}
  selector:
    matchLabels:
      {{- include "zeo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zeo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: {{ .Release.Name }}-chownplone
          command:
            - "chown"
            - "plone:plone"
            - "/data"
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - mountPath: /data
              name: data  
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Release.Name }}-zeoserver
          env:
            {{- range .Values.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"{{ end }}
          ports:
            - name: zeo
              containerPort: 8100
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            runAsUser: 500
          volumeMounts:
            - mountPath: /data
              name: data
          livenessProbe:
            tcpSocket:
              port: 8100
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8100
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "zeo.fullname" . }}-data
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
